#!/usr/bin/env sh

formula git
formula tig
formula diff-so-fancy

dot::symlink "$XDG_CONFIG_HOME/git/config" "$DOT_PLUGIN_DIR/etc/gitconfig"
dot::symlink "$XDG_CONFIG_HOME/git/ignore" "$DOT_PLUGIN_DIR/etc/gitignore"

dot::symlink "$XDG_CONFIG_HOME/tig/config" "$DOT_PLUGIN_DIR/etc/tigrc"
