#!/usr/bin/env sh

if dot::os::mac; then
  formula curl

  # We don't use `brew link --force curl` as Homebrew explicitly forbids
  # linking macOS-provided software.
  #
  # You'll still need to remember to explicitly specify includes/headers if you
  # want to compile against the newer curl version instead of the system one
  dot::symlink "$(brew --prefix)/bin/curl" "$(brew --prefix curl)/bin/curl"
fi
