#!/usr/bin/env bash

cask_installed() {
  cask="$1"
  ! brew info --cask "$cask" >/dev/null 2>&1
}

install_cask() {
  cask="$1"
  if ! cask_installed "$cask"; then
    brew install --cask "$cask"
  fi
}

uninstall_cask() {
  cask="$1"
  if cask_installed "$cask"; then
    brew uninstall --cask "$cask"
  fi
}

cask() {
  cask="$1"
  if dot::installing; then
    install_cask "$cask"
  else
    uninstall_cask "$cask"
  fi
}

cask "$@"
